### ISSUE TITLE
Adicionar botão float de Wpp

### ISSUE THREAD

**Issue by benedictotavio** [benedictotavio/projeto_bushido_frontend#11]
- Remover botões de WPP.para um botão float
  - **PATH**: src/app/pages/karate-sem-fronteiras/karate-sf-oficinas/karate-sf-oficinas.component.html
  - refatorar os botões para um float
  - ![Screenshot from 2024-01-02 12-44-48](https://github.com/benedictotavio/projeto_bushido_frontend/assets/79219098/3ca09a34-17c1-4d7e-874e-cab1f9cb3c32)

**Comment by diesantana** [comment]
- O botão deve ficar apenas neste componente ou em toda a aplicação? 
- a area de contato onde temos dois botões de whats, contendo dois números, continuam ou deverão ser removidos?
