### ISSUE TITLE
alterar sistema de variavel de ambiente

### ISSUE THREAD

**Issue by benedictotavio** [benedictotavio/projeto_bushido_frontend#30]
O código usa enviroment.ts para variaveis de ambiente em dev
- alterar o codigo pra utilizar .env
- OPÇÃO 1: uso de variaveis de ambiente vindo da actions do github ${{vars.TOKEN}}.
- OPÇÃO 2: usar variaveis do env vindo do git ops
- **Path:** src/enviroments/enviroment
- configurar ``` datoToken: '7176c17699c1a61a100c9a7d35d69a' ``` para uma variavel de ambiente.

**Comment by PauloCesardev99** [comment]
Não tenho acesso aos  secrets do github actions para configurar o DatoToken.
