### ISSUE TITLE
Menu lateral no dashboard

### ISSUE THREAD

**Issue by benedictotavio** [benedictotavio/projeto_bushido_frontend#32]
- Na rota de dashboard : ``` /admin/:email```. inicialmente devemos retirar o cabeçalho principal e rodapé.
  - Apos a remoção, adicione um menu lateral interativo com as determinadas funções
    - Alunos
      - Adicionar aluno
      - Lista de turmas
      - Buscar aluno

**OBS**: seguir a risca o modelo de menu abaixo
Exemplo:
    
![magento_menu](https://github.com/benedictotavio/projeto_bushido_frontend/assets/79219098/e13bcff7-8f93-4d06-8209-201e71c2954f)

**Comment by PauloCesardev99** [comment]
Otávio, pode ser assim? 

![sidebar-alternativo](https://github.com/benedictotavio/projeto_bushido_frontend/assets/122824870/a8efdd69-d8e8-47df-8c7c-aacfac7ec3c3)

**Comment by benedictotavio** [comment]
Podemos deixar assim mesmo inicialmente, se tivermos mais features, ou mais entidades... Podemos refatoramos, mas esta muito bom mesmo.
- **Obs:** Não esqueça de colocar a botão de logout, para o admin sair do dashboard. _Ele deve retornar para a tela de login_.
