### ISSUE TITLE
correções no cabeçalho

### ISSUE THREAD

**Issue by benedictotavio** [benedictotavio/projeto_bushido_frontend#6]
**Descrição**
Fazer alterações estruturais no cabeçalho

**Descrição Técnica**

1. Redefinir configurações de fonte
- **tamanho**: 1em
- **estilo**: Roboto
- **hover**: fundo azul, texto branco
- ![menu_header](https://github.com/benedictotavio/projeto_bushido_frontend/assets/79219098/aba9446a-a7f5-4bf1-9feb-c63ad95e4c1a)

2. Consertar toggle menu
- consertar menu para função dropdown list
- ![menu_responsivo](https://github.com/benedictotavio/projeto_bushido_frontend/assets/79219098/b473cd40-f1c4-4364-b8a3-120a919dd4b0)

**Comment by PauloCesardev99** [comment]
Achei estranho o menu dropdown parar de funcionar.

**Comment by PauloCesardev99** [comment]
Existe 3 tipos de navbar em bootstrap: https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes  

Nota: Para fazer igual a da imagem, teria que refazer em css puro.

**Comment by benedictotavio** [comment]
Podemos utilizar o mesmo cabeçalho bootstrap, apenas remover o campo de busca
